driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/groove-dl']

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: debian-7.1
    run_list: apt::default
  - name: centos-6.5
  - name: windows-7
    driver_config:
      box: windows-7
      box_url: http://vagrantboxes.devopslive.org/windows-7-enterprise-i386.box

suites:
  - name: default
    run_list: omnibus::default
