driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/groove-dl']

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: debian-7.1
    run_list: apt::default
  - name: centos-6.5
  - name: windows-8.1
    driver_config:
      box: windows-8.1
      box_url: http://cdn.box-cutter.com/windows/virtualbox4.3.20/eval-win81x64-enterprise-nocm-1.0.2.box

suites:
  - name: default
    run_list: omnibus::default
