AllCops:
  Exclude:
    - bin/**/*
Metrics/LineLength:
  Enabled: false
Style/FileName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
